version: "3.8"
# un nouveau commentaire
volumes:
  mariaimmo: #déclaration du volume pour la base

services:

  # container de bdd
  immobase: #nom de service
    container_name: ${DB_CONTAINER_NAME}
    image: mariadb:latest
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mariaimmo:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: ${TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  # container php
  immophp:
    container_name: ${PHP_CONTAINER_NAME}
    build:
      context: ./php
#    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '${PHP_PORT}:9000'
    environment:
      DEBUG: '1'
      PHP_DISPLAY_ERRORS: '1'
      PHP_POST_MAX_SIZE: '100M'
      PHP_UPLOAD_MAX_FILESIZE: '100M'
      TZ: ${TIMEZONE}
    volumes:
      - ./app:/var/www/html
    depends_on:
      - immobase

  # service node
  immonode:
    tty: true
    container_name: ${NODE_CONTAINER_NAME}
    build:
      context: ./node
    volumes:
      - ./app:/var/www/html
    restart: always
    environment:
      TZ: ${TIMEZONE}
    depends_on:
      - immophp

  # server web
  immonginx:
    container_name: ${NGINX_CONTAINER_NAME}
    image: nginx:stable-alpine
#    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    restart: always
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx/
    depends_on:
      - immophp
      - immobase
      - immonode
